### PR TITLE
10 Rename 'gnd' field on item view

### LINKED ISSUE #10: Rename 'gnd' field on item view
### Current

image

### New

The field title of the second link field should read "DNB-Portal" instead of "gnd".

image

### PR DESCRIPTION
**Pull request by flicksolutions**
https://github.com/DHBern/becher-frontend/issues/10

### CODE REVIEW

**Comment by flicksolutions** [comment]
I introduced a linkstructure.json that translates keys to labels similar to the structure.json that already exists.

**Comment by pdaengeli** [comment]
LGTM

Does it make sense to integrate `linkstructure.json` into `structure.json` or is it more convenient to keep them separate?

**Comment by flicksolutions** [comment]
keeping it separate was more convenient to integrate. But you are right, that it possibly makes sense to have it in the same file. The reason I didn't do it is because I wasn't sure of how the new structure.json would look like?

Would it be something like this:
```json
[
  {
     "key": "fieldstructure",
     "content": _content of the old structure.json_
  },
  {
     "key": "linkstructure",
     "content": _content of the linkstructure.json_
  },
]
```
would that make more sense?

**Comment by pdaengeli** [comment]
Yes, that's how it could look like. But let's keep it simple for now and as a separate `linkstructure.json` living directly in this repo.

**Comment by flicksolutions** [comment]
just for fun: could you then **approve** this PR?

click on "Files Changed" and then on the green button to finish your review. :-)
grafik

**Review by pdaengeli — APPROVED** [review]

**Pull request merged**
